// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Tile.h"
#include "GameField.generated.h"


// Define the available pathfinding logic types
UENUM(BlueprintType)
enum class EPathfindingAlgorithm : uint8
{
	// Guarantees the shortest path by balancing travel cost (G) and heuristic distance (H)
	AStar   UMETA(DisplayName = "A*"),

	// Prioritizes speed by following the heuristic distance (H) exclusively; non-optimal
	Greedy  UMETA(DisplayName = "Greedy")
};

UCLASS()
class APEX_TRINITY_API AGameField : public AActor // KEEP THIS LINE AS GENERATED BY UNREAL
{
	GENERATED_BODY()
	
public:	
	// Sets default values for this actor's properties
	AGameField();

	// Calculate the Manhattan distance between two grid coordinates
	int32 GetManhattanDistance(const FVector2D& Start, const FVector2D& End) const;

	// 1D Array tracking all tiles (Transient because filled at runtime)
	UPROPERTY(Transient)
	TArray<ATile*> TileArray;

	// Map for fast access to tiles via (X,Y) coordinates
	UPROPERTY(Transient)
	TMap<FVector2D, ATile*> TileMap;

	// Grid size (25x25 from specs)
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Config")
	int32 Size;

	// Physical dimension of a single tile
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Config")
	float TileSize;

	// Percentage spacing between tiles
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Config")
	float CellPadding;

	// Multiplier used to calculate the offset between tiles
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Config")
	float NextCellPositionMultiplier;

	// TSubclassOf ensures type-safety in the Editor
	UPROPERTY(EditDefaultsOnly, Category = "Config")
	TSubclassOf<ATile> TileClass;

	// The blueprint class to instantiate for the towers
	UPROPERTY(EditDefaultsOnly, Category = "Config")
	TSubclassOf<class ATower> TowerClass;

	// Classes to spawn for the units
	UPROPERTY(EditDefaultsOnly, Category = "Config")
	TSubclassOf<class AUnit> SniperClass;

	UPROPERTY(EditDefaultsOnly, Category = "Config")
	TSubclassOf<class AUnit> BrawlerClass;

	void HighlightMovementTiles(class AUnit* SelectedUnit);

	void HighlightAttackableTiles(class AUnit* SelectedUnit);

	void ClearHighlights();

	void HighlightDeploymentZone(int32 TeamID);

	// Identify the 4 adjacent neighbor tiles (North, South, East, West)
	TArray<class ATile*> GetAdjacentTiles(class ATile* CenterTile) const;

	// Generate the path tree by calculating elevation change costs
	TArray<class ATile*> GetReachableTiles(class AUnit* Unit) const;

	// Finds the nearest walkable tile to a target coordinate using Manhattan distance.
	// Essential for the adaptive fallback if the ideal position is water (Level 0)
	ATile* GetClosestValidTile(int32 TargetX, int32 TargetY);

	// A* algorithm
	TArray<class ATile*> FindPath(class ATile* StartNode, class ATile* EndNode);

	// Greedy best-first search heuristic algorithm (bonus requirement)
	// Prioritizes nodes based solely on the estimated distance to the destination (Heuristic)
	TArray<class ATile*> FindPathGreedy(class ATile* StartNode, class ATile* EndNode);

	// Converts (X, Y) grid coordinates into the alphanumeric format specified in the GDD (e.g., X=1, Y=4 becomes "B4")
	FString GetAlphanumericCoordinate(FVector2D GridPosition) const;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Map Settings")
	float WaterThreshold = 0.30f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Map Settings")
	float GrassThreshold = 0.45f;

	// Threshold separating Mountain1 (lvl  2) from Mountain2 (lvl 3)
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Map Settings")
	float Mountain1Threshold = 0.55f;

	// Threshold separating Mountain2 (lvl 3) from Mountain3 (lvl 4)
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Map Settings")
	float Mountain2Threshold = 0.65f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Map Settings")
	float NoiseScale = 0.15f;

	// Main function generating the procedural game field
	UFUNCTION(BlueprintCallable, Category = "Map Generation")
	void GenerateField();

	// Main function generating the procedural game field
	UFUNCTION(BlueprintCallable, Category = "Map Generation")
	void ClearField();

	UFUNCTION(BlueprintCallable, Category = "Pathfinding")
	TArray<ATile*> GeneratePathRoute(ATile* StartNode, ATile* EndNode);

	// Exposed to the editor to allow designers to toggle the navigation logic globally or per-instance
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Pathfinding")
	EPathfindingAlgorithm SelectedAlgorithm = EPathfindingAlgorithm::AStar;

protected:
	// Called when an instance of this class is placed in the editor or spawned
	virtual void OnConstruction(const FTransform& Transform) override;

	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

	// Executes the Symmetric Adaptive Placement Algorithm for the 3 towers
	void SpawnTowers();

	// Calculates 3D world position given grid (X,Y) and elevation (Z)
	FVector GetRelativeLocationByXYPosition(const int32 InX, const int32 InY, const int32 InZ) const;

	// Maps a Perlin noise value (-1.0 to 1.0) into 5 elevation steps (0 to 4)
	int32 QuantizePerlinNoise(const float NoiseValue) const;
};